Screenful.Loc={
  howmany: function(n){ return n+" iontráil"; },
  ready: "Réidh.",
  filter: "Scag",
  removeFilter: "Bain scagaire",
  reload: "Athlódáil",
  cancel: "Cealaigh",
  more: "Tuilleadh",
  new: "Nua",
  edit: "Athraigh",
  save: "Sábháil",
  delete: "Scrios",
  listing: "Liosta á fháil...",
  listingFailed: "Níor éirigh liom liosta a fháil.",
  reading: "Sonraí á fáil...",
  readingFailed: "Ní ann don iontráil.",
  saving: "Á shábháil...",
  savingFailed: "Níor éirigh liom na sonraí a shǎbháil.",
  deleting: "Á scrios...",
  deletingFailed: "Níor éirigh liom na sonraí a scrios.",
  deleteConfirm: "Cúramach anois! An bhfuil tú cinnte?",
  username: "Seoladh ríomhphoist",
  password: "Pasfhocal",
  login: "logáil isteach",
  loginError: "Seoladh ríomhphoist mícheart nó pasfhocal mícheart.",
  logout: "Logáil amach",
  anonymous: "úsáideoir anaithnid",
};
