Screenful.Loc={
  howmany: function(n){
  	if(n==1) return n+" heslo";
  	if(n>1 && n<5) return n+" hesla";
  	return n+" hesel";
  },
  ready: "Hotovo.",
  filter: "Filtrovat",
  removeFilter: "Odstranit filtr",
  reload: "Obnovit",
  cancel: "Storno",
  more: "Víc",
  new: "Nové",
  edit: "Upravit",
  save: "Uložit",
  delete: "Smazat",
  listing: "Čekáme na seznam ze serveru...",
  listingFailed: "Nepovedlo se získat seznam ze serveru.",
  reading: "Čekáme na data ze serveru...",
  readingFailed: "Neexistuje.",
  saving: "Ukládá se...",
  savingFailed: "Nepovedlo se to uložit.",
  deleting: "Maže se...",
  deletingFailed: "Nepovedlo se to smazat.",
  deleteConfirm: "Pozor s tímhle! Opravdu to chceš smazat?",
  username: "E-mailová adresa",
  password: "Heslo",
  login: "Přihlásit se",
  loginError: "Nesprávná e-mailová adresa nebo nesprávné heslo.",
  logout: "Odhlásit se",
  anonymous: "anonymní uživatel",
  home: "Domů",
  title: "Nadpis",
  titleEmpty: "Nadpis by neměl být prázdný.",
  url: "URL",
  urlEmpty: "URL by nemělo být prázdné.",
  urlShort: "URL by mělo být aspoň tři znaky dlouhé.",
  urlInvalid: "URL smí obsahovat jen znaky a-z, A-Z, 0-9 a pomlčku.",
  urlTaken: "Toto URL už je obsazené.",
  template: "Šablona",
  create: "Vytvořit",
};
