Screenful.Loc={
  howmany: function(n){ if(n==1) return n+" entry"; return n+" entries"; },
  ready: "Ready.",
  filter: "Filter",
  removeFilter: "Clear filter",
  reload: "Reload",
  cancel: "Cancel",
  more: "More",
  new: "New",
  edit: "Edit",
  save: "Save",
  delete: "Delete",
  listing: "Getting list of entries...",
  listingFailed: "Failed to get list of entries.",
  reading: "Getting entry...",
  readingFailed: "No such entry.",
  saving: "Saving entry...",
  savingFailed: "Failed to save entry.",
  deleting: "Deleting entry...",
  deletingFailed: "Failed to delete entry.",
  deleteConfirm: "Careful now! Are you sure?",
  username: "E-mail address",
  password: "Password",
  login: "Log in",
  loginError: "Incorrect e-mail address or password.",
  logout: "Log out",
  anonymous: "anonymous user",
};
