Screenful.Loc={
  howmany: function(n){ return n+" iontráil"; },
  ready: "Réidh.",
  filter: "Scagaire...",
  reload: "Athlódáil",
  cancel: "Cealaigh",
  go: "Gabh",
  more: "Tuilleadh",
  new: "Nua",
  edit: "Athraigh",
  save: "Sábháil",
  delete: "Scrios",
  listing: "Liosta iontrálacha á fháil...",
  listingFailed: "Níor éirigh liom liosta iontrálacha a fháil.",
  reading: "Iontráil á fáil...",
  readingFailed: "Ní ann don iontráil.",
  saving: "Iontráil á sábháil...",
  savingFailed: "Níor éirigh liom an iontráil a shǎbháil.",
  deleting: "Iontráil á scrios...",
  deletingFailed: "Níor éirigh liom an iontráil a scrios.",
  deleteConfirm: "Cúramach anois! An bhfuil tú cinnte?",
};
