Screenful.Loc={
  howmany: function(n){ if(n==1) return n+" entry"; return n+" entries"; },
  ready: "Ready.",
  filter: "Filter",
  removeFilter: "Clear filter",
  reload: "Reload",
  cancel: "Cancel",
  more: "More",
  new: "New",
  edit: "Edit",
  save: "Save",
  delete: "Delete",
  listing: "Getting list...",
  listingFailed: "Failed to get list.",
  reading: "Getting item...",
  readingFailed: "No such item.",
  saving: "Saving...",
  savingFailed: "Failed to save.",
  deleting: "Deleting...",
  deletingFailed: "Failed to delete.",
  deleteConfirm: "Careful now! Are you sure?",
  username: "E-mail address",
  password: "Password",
  login: "Log in",
  loginError: "Incorrect e-mail address or password.",
  logout: "Log out",
  anonymous: "anonymous user",
};
